In [9]:
# imports

import os 
import requests 
import pandas as pd
import numpy as np
import json

In [10]:
# Vancouver bike stations from part 1: 

van_bikes = pd.read_csv('C:/Users/sherr/LHL classwork/LHL-P2/data/van_bikes.csv')

# Foursquare

Send a request to Foursquare with a small radius (1000m) for all the bike stations in your city of choice.

In [11]:
# Category IDs:

restaurant_id = '4d4b7105d754a06374d81259'
pilates_id = '5744ccdfe4b0c0459246b4b2'

In [41]:
url = 'https://api.foursquare.com/v3/places/search?'
api_key = os.environ['FOURSQUARE_API_KEY']
headers = {'Accept': 'application/json'}
headers['Authorization'] = api_key

fsq_restaurants = []
fsq_pilates = []

for row in van_bikes.itertuples(index=False):
    
    lat = row.latitude
    long = row.longitude 
    ll = f'{lat},{long}'
    
    r_params = {'ll': ll,
                'radius': 1000,
                'categories': restaurant_id}

    p_params = {'ll': ll, 
              'radius': 1000,
              'categories': pilates_id}
    
    r_request = requests.get(url, headers=headers, params=r_params)
    r_results = r_request.json()['results']
    r_df = pd.json_normalize(r_results)
    fsq_restaurants.append(r_df)
    
    p_request = requests.get(url, headers=headers, params=p_params)
    p_results = p_request.json()['results']
    p_df = pd.json_normalize(p_results)
    fsq_pilates.append(p_df)

Parse through the response to get the POI (such as restaurants, bars, etc) details you want (ratings, name, location, etc)

In [48]:
#  I am interested in finding the nearest and furthest restaurant/pilates studio from each bike station, their respective distances from the station, as well each station's 
#  average distance to its closest restaurant/pilates studio

nearest_rdists = []
nearest_rnames = []
furthest_rdists = []
furthest_rnames = []
avg_rdists = []

nearest_pdists = []
nearest_pnames = []
furthest_pdists = []
furthest_pnames = []
avg_pdists = []

for i, row in van_bikes.iterrows():
    r_df = fsq_restaurants[i]
    nearest_rdist = r_df['distance'].min()
    nearest_rname = r_df.sort_values('distance').iloc[0]['name']
    furthest_rdist = r_df['distance'].max()
    furthest_rname = r_df.sort_values('distance', ascending=False).iloc[0]['name']
    avg_rdist = round((sum(list(r_df['distance'])) / len(r_df)), 2)

    p_df = fsq_pilates[i]
    if 'distance' in p_df.columns:
        nearest_pdist = p_df['distance'].min()
        furthest_pdist = p_df['distance'].max()
        avg_pdist = round(sum(list(p_df['distance'])) / len(p_df), 2)
    else:
        nearest_pdist = None
        furthest_pdist = None
        avg_pdist = None
        
    if 'name' in p_df.columns: 
        nearest_pname = p_df.sort_values('distance').iloc[0]['name']
        furthest_pname = p_df.sort_values('distance', ascending=False).iloc[0]['name']
    else:
        nearest_pname = None
        furthest_pname = None

    nearest_rdists.append(nearest_rdist)
    nearest_rnames.append(nearest_rname)
    furthest_rdists.append(furthest_rdist)
    furthest_rnames.append(furthest_rname)
    avg_rdists.append(avg_rdist)
    
    nearest_pdists.append(nearest_pdist)
    nearest_pnames.append(nearest_pname)
    furthest_pdists.append(furthest_pdist)
    furthest_pnames.append(furthest_pname)
    avg_pdists.append(avg_pdist)

Put your parsed results into a DataFrame

In [55]:
foursquare_df = pd.DataFrame({'name': van_bikes['station_name'],
              'timestamp': van_bikes['timestamp'],
              'free_bikes': van_bikes['free_bikes'],
              'empty_slots': van_bikes['empty_slots'],
              'nearest_rdist': nearest_rdists,
              'nearest_rname': nearest_rnames,
              'furthest_rdist': furthest_rdists,
              'furthest_rname': furthest_rnames,
              'avg_rdist': avg_rdists,
              'nearest_pdist': nearest_pdists,
              'nearest_pname': nearest_pnames,
              'furthest_pdist': furthest_pdists,
              'furthest_pname': furthest_pnames,
              'avg_pdist': avg_pdists})

In [54]:
foursquare_df.head()

,name,timestamp,free_bikes,empty_slots,nearest_rdist,nearest_rname,furthest_rdist,furthest_rname,avg_rdist,nearest_wdist,nearest_wname,furthest_wdist,furthest_wname,avg_wdist
0,Chilco & Barclay,2025-05-13T06:28:19.789503+00:00Z,17,1,299,Peaked Pies,869,The Inukshuk,492.1,552.0,Pilates Unlimited Fitness,552.0,Pilates Unlimited Fitness,552.0
1,St George & Broadway,2025-05-13T06:28:20.016492+00:00Z,4,9,304,Sushiyama,906,33 Acres Brewing Co,582.4,329.0,Vancouver Pilates Process Inc,859.0,Union Pilates,594.0
2,Britannia Parking Lot,2025-05-13T06:28:20.014847+00:00Z,1,12,214,The Lunch Lady,612,A. Bosa and Company Ltd. Import Euro,429.2,836.0,Dharmalab,836.0,Dharmalab,836.0
3,Morton & Denman,2025-05-13T06:28:19.634075+00:00Z,12,14,72,Marble Slab Creamery,668,Hokkaido Ramen Santouka,318.2,735.0,Pilates Unlimited Fitness,735.0,Pilates Unlimited Fitness,735.0
4,Thornton & National,2025-05-13T06:28:20.014996+00:00Z,10,4,552,Torafuku,902,Keefer Bar,744.6,NaN,None,NaN,None,NaN

# Yelp

Send a request to Yelp with a small radius (1000m) for all the bike stations in your city of choice.

In [24]:
url = 'https://api.yelp.com/v3/businesses/search?categories=&sort_by=best_match&limit=10'
api_key = os.environ["YELP_API_KEY"]
headers = {'Accept': 'application/json',
           'Authorization': f'Bearer {api_key}'}

yelp_restaurants = []
yelp_pilates = []

for row in van_bikes.itertuples(index=False):
    latitude = row.latitude
    longitude = row.longitude

    r_params = {'latitude': latitude,
                'longitude': longitude,
                'radius': 1000,
                'term': 'restaurant'}
    
    p_params = {'latitude': latitude,
                'longitude': longitude,
                'radius': 1000,
                'term': 'pilates'}   
    
    r_result = requests.get(url, headers=headers, params=r_params)
    r_data = r_result.json()['businesses']
    r_columns = [{'name': r['name'],
                 'address': r['location']['address1'],
                 'distance': r['distance'],
                 'reviews': r['review_count'],
                 'rating': r['rating'],
                 'price': r.get('price')} for r in r_data]
    r_df = pd.DataFrame(r_columns)
    yelp_restaurants.append(r_df)

    p_result = requests.get(url, headers=headers, params=p_params)
    p_data = p_result.json()['businesses']
    p_columns = [{'name': p['name'],
                 'address': p['location']['address1'],
                 'distance': p['distance'],
                 'reviews': p['review_count'],
                 'rating': p['rating'],
                 'price': p.get('price')} for p in p_data]
    p_df = pd.DataFrame(p_columns)   
    yelp_pilates.append(p_df)

Parse through the response to get the POI (such as restaurants, bars, etc) details you want (ratings, name, location, etc)

In [62]:
# I am interested in looking at the average ratings of restaurants/pilates studios in radius of each station and their average distances to the station.
# I also want to find the best rated(if tied then more reviews) and most reviewed restaurant/pilates studios in radius.

avg_rratings = []
avg_rdists = []
best_rratingnames = []
best_rratings = []
best_rdists = []


avg_pratings = []
avg_pdists = []
best_pratingnames = []
best_pratings = []
best_pdists = []

for i, row in van_bikes.iterrows():
    
    r_df = yelp_restaurants[i]
    avg_rrating = round(r_df['rating'].mean(), 2)
    avg_rdist = round(r_df['distance'].mean(), 2)
    best_rratingname = r_df.sort_values(['rating', 'reviews'], ascending=[False, False])['name'].values[0]
    best_rrating = r_df.sort_values(['rating', 'reviews'], ascending=[False, False])['rating'].values[0]
    best_rdist = r_df.sort_values(['rating', 'reviews'], ascending=[False, False])['distance'].values[0]

    p_df = yelp_pilates[i]
    if 'rating' in p_df.columns and 'distance' in p_df.columns and 'reviews' in p_df.columns:
        avg_prating = round(p_df['rating'].mean(), 2)
        avg_pdist = round(p_df['distance'].mean(), 2)
        best_pratingname = p_df.sort_values(['rating', 'reviews'], ascending=[False, False])['name'].values[0]
        best_prating = p_df.sort_values(['rating', 'reviews'], ascending=[False, False])['rating'].values[0]
        best_pdist = p_df.sort_values(['rating', 'reviews'], ascending=[False, False])['distance'].values[0]

    else:
        avg_prating = None
        avg_pdist = None
        best_pratingname = None
        best_prating = None
        best_pdist = None 

    avg_rratings.append(avg_rrating)
    avg_rdists.append(avg_rdist)
    best_rratingnames.append(best_rratingname)
    best_rratings.append(best_rrating)
    best_rdists.append(best_rdist)
    
    avg_pratings.append(avg_prating)
    avg_pdists.append(avg_pdist)
    best_pratingnames.append(best_pratingname)
    best_pratings.append(best_prating)
    best_pdists.append(best_pdist)

Put your parsed results into a DataFrame

In [63]:
yelp_df = pd.DataFrame({'station_name': van_bikes['station_name'],
                        'timestamp': van_bikes['timestamp'],
                        'free_bikes': van_bikes['free_bikes'],
                        'empty_slots': van_bikes['empty_slots'],
                        'avg_rrating': avg_rratings,
                        'avg_rdist': avg_rdists,
                        'best_rratingname': best_rratingnames,
                        'best_rrating': best_rratings,
                        'best_rdist': best_rdists,
                        'avg_prating': avg_pratings,
                        'avg_pdist': avg_pdists,
                        'best_pratingname': best_pratingnames,
                        'best_prating': best_pratings,
                        'best_pdist': best_pdists})

yelp_df.to_csv('C:/Users/sherr/LHL classwork/LHL-P2/data/yelp_df.csv', index=False)

In [65]:
yelp_df.head()

,station_name,timestamp,free_bikes,empty_slots,avg_rrating,avg_rdist,best_rratingname,best_rrating,best_rdist,avg_prating,avg_pdist,best_pratingname,best_prating,best_pdist
0,Chilco & Barclay,2025-05-13T06:28:19.789503+00:00Z,17,1,4.35,399.19,Noah's Cafe,4.7,406.975784,2.86,1249.29,The Well by Kunye,5.0,777.755119
1,St George & Broadway,2025-05-13T06:28:20.016492+00:00Z,4,9,4.15,460.69,Mercato Di Luigi,4.5,322.184364,2.81,1235.53,Evolution Fitness and Lagree,5.0,1381.878329
2,Britannia Parking Lot,2025-05-13T06:28:20.014847+00:00Z,1,12,4.30,326.73,Magari by Oca,5.0,332.892353,4.00,573.07,Spartacus Gym,4.0,573.065975
3,Morton & Denman,2025-05-13T06:28:19.634075+00:00Z,12,14,4.34,236.96,Noah's Cafe,4.7,155.258150,3.44,1346.82,The Well by Kunye,5.0,913.784194
4,Thornton & National,2025-05-13T06:28:20.014996+00:00Z,10,4,4.21,882.60,The Darkside,4.7,635.340115,4.10,1395.51,Reform Pilates,5.0,1694.888580

# Comparing Results

Which API provided you with more complete data? Provide an explanation.

Yelp API provided me with more complete data, because it is able to show all the information that Foursquare shows in addition to showing the rating and number of reviews.

Get the top 10 restaurants according to their rating

In [66]:
yelp_rdf.sort_values('rating', ascending=False).head(10)

,name,address,distance,reviews,rating,price
1647,Magari by Oca,1260 Commercial Drive,1186.615969,4,5.0,None
969,Tops Chef Persian Restaurant,555 W 12th Ave,212.489745,2,5.0,None
1599,Uncle Pu's Sichuan Taste,3132 West Broadway,91.481523,2,5.0,None
1676,Magari by Oca,1260 Commercial Drive,1066.486922,4,5.0,None
1555,Kapow Burger,20 East 4th Avenue,135.191785,1,5.0,None
116,Mon Garenne,4021 Macdonald Street,1112.240981,1,5.0,None
1574,Word.,555 Great Northern Way,206.110225,1,5.0,None
1849,Magari by Oca,1260 Commercial Drive,1392.302350,4,5.0,None
1089,Magari by Oca,1260 Commercial Drive,714.157338,4,5.0,None
1843,Pho Jade,987 Hastings Street E,158.709788,1,5.0,None